# Importar Lib's

In [1]:
import os
import openpyxl
import pandas as pd
import ipywidgets as widgets
import numpy as np
from IPython.display import display
from datetime import datetime
from ipywidgets import interact
from openpyxl import Workbook

# Passo 1: Listar arquivos PDF em uma pasta específica

In [2]:
diretorio_lote = r"C:\Users\helym\OneDrive - ONE ENGENHARIA INDUSTRIA E COMERCIO LTDA\OeM\OeM\00-INTELBRAS\000_Relatórios de Campo\001 RELATORIOS ENVIADOS\AC\1.0-CORRETIVA\1ªTRACHE"
#"C:\Users\HELY-DELL\OneDrive - ONE ENGENHARIA INDUSTRIA E COMERCIO LTDA\OeM\OeM\00-INTELBRAS\000_Relatórios de Campo\001 RELATORIOS ENVIADOS\1.0-CORRETIVA\2ªTRANCHE"

In [3]:
df_filtered_global_oem = None

def ler_planilha():
    """Lê uma planilha do Excel."""
    excluir_status = ['TREINAMENTO','DUPLICADO','CANCELADO ']
    df_bd = pd.read_excel(r"C:\Users\helym\projetos_python\jupyter\OEM\content\base_sip_Concluido.xlsx")
    df = df_bd[~df_bd['STATUS'].isin(excluir_status)]
    return df

def aplicar_filtros(rota_value, status_value, tipo_value, executor_value, origem_value, tipocausa_value, data_inicial, data_final):
    """Aplica filtros a uma planilha."""
    global df_filtered_global_oem
    df_filtered_global_oem = df[
        df["ROTA"].isin(rota_value) &
        df["STATUS"].isin(status_value) &
        df["TIPO"].isin(tipo_value) &
        df["EXECUTOR"].isin(executor_value) &
        df["ORIGEM"].isin(origem_value) &
        df["TIPOCAUSA"].isin(tipocausa_value) &
        (df["DATACONCLUSAO"] >= data_inicial) &
        (df["DATACONCLUSAO"] <= data_final)
    ]
    return df_filtered_global_oem

if __name__ == "__main__":
    df = ler_planilha()

    df["DATACONCLUSAO"] = pd.to_datetime(df["DATACONCLUSAO"]).dt.date

    rota_options = sorted(list(df['ROTA'].unique()))
    rota_filter = widgets.SelectMultiple(options=rota_options, description="Rotas:")

    status_options = sorted(list(df['STATUS'].unique()))
    status_filter = widgets.SelectMultiple(options=status_options, description="Status:")

    tipo_options = sorted(list(df['TIPO'].unique()))
    tipo_filter = widgets.SelectMultiple(options=tipo_options, description="Tipo:")

    executor_options = sorted(list(df['EXECUTOR'].unique()))
    executor_filter = widgets.SelectMultiple(options=executor_options, description="Usuário:")

    origem_options = sorted(list(df['ORIGEM'].unique()))
    origem_filter = widgets.SelectMultiple(options=origem_options, description="Origem:")

    tipocausa_options = sorted(list(df['TIPOCAUSA'].unique()))
    tipocausa_filter = widgets.SelectMultiple(options=tipocausa_options,descrition="Tipo Causa")

    data_inicial_filter = widgets.DatePicker(value=df["DATACONCLUSAO"].min())
    data_final_filter = widgets.DatePicker(value=df["DATACONCLUSAO"].max())

    aplicar_filter_button = widgets.Button(description="Aplicar filtros")

    def on_button_click(event):
        global df_filtered_global_oem
        df_filtrado = aplicar_filtros(
            rota_filter.value, status_filter.value, tipo_filter.value,
            executor_filter.value, origem_filter.value,
            tipocausa_filter.value,
            data_inicial_filter.value, data_final_filter.value
        )
        df_filtered_global_oem = df_filtrado

    aplicar_filter_button.on_click(on_button_click)

    display(data_inicial_filter)
    display(data_final_filter)
    df_filtered_global_oem
    display(
        widgets.HBox([origem_filter, tipo_filter, rota_filter, executor_filter, status_filter],
                     layout=widgets.Layout(align_items='baseline'))
    )
    display(
        widgets.HBox([tipocausa_filter, aplicar_filter_button],
                     layout=widgets.Layout(align_items='center'))
    )

DatePicker(value=datetime.date(2022, 1, 1), step=1)

DatePicker(value=datetime.date(2024, 5, 2), step=1)

HBox(children=(SelectMultiple(description='Origem:', options=('ENERGISA', 'FORNECEDOR', 'ONE ENGENHARIA'), val…

HBox(children=(SelectMultiple(options=('CABOS ROMPIDOS', 'EQUIPAMENTOS DANIFICADOS', 'FALHA DE BATERIAS', 'INT…

## Pasta contendo os arquivos PDF

In [4]:
def encontrar_duplicados(numocorrencia):
    duplicados = numocorrencia[numocorrencia.duplicated(subset='NUMOCORRENCIA')]
    return duplicados

arquivos_pdf = []
for raiz, diretorios, arquivos in os.walk(diretorio_lote):
    for arquivo in arquivos:
        if arquivo.endswith('.pdf'):
            arquivos_pdf.append(os.path.join(raiz, arquivo))

string = pd.DataFrame(pd.Series(arquivos_pdf).str.extract(r"(\d+)_(\d+)_(.+)_(.+)_(.+)_(.+)"))
string.rename(columns={1: 'NUMOCORRENCIA'}, inplace=True)
numocorrence = string[['NUMOCORRENCIA']].astype('float')  # Convertendo para float para acomodar NaN

# Contagem total de duplicatas
duplicadas_count = numocorrence[numocorrence.duplicated(subset='NUMOCORRENCIA')].shape[0]

# Encontrar duplicatas
date_duplicated= encontrar_duplicados(numocorrence.copy())  # Cria uma cópia independente
date_duplicated.dropna(inplace=True)  # Remove NaNs do DataFrame duplicatas
date_duplicated['NUMOCORRENCIA'] = date_duplicated['NUMOCORRENCIA'].astype('int')  # Convertendo de volta para int
# Mesclando os dados principais.
df_pdf = numocorrence.merge(df_filtered_global_oem, left_on='NUMOCORRENCIA', right_on='NUMOCORRENCIA', how='left' )
df_pdf = df_pdf[['NUMOS', 'UC','IDSIGFI','NUMOCORRENCIA','NOMECLIENTE','ROTA','STATUS','EXECUTOR','DTCONCLUSAO']]
print("Número total de duplicatas:", duplicadas_count)
print("Duplicatas encontradas após remoção de NaN:")
display(df_pdf)

Número total de duplicatas: 0
Duplicatas encontradas após remoção de NaN:

Empty DataFrame
Columns: [NUMOS, UC, IDSIGFI, NUMOCORRENCIA, NOMECLIENTE, ROTA, STATUS, EXECUTOR, DTCONCLUSAO]
Index: []

# Lista de arquivos PDF na pasta

# Passo 2: Ler o arquivo Excel com a lista de arquivos

In [5]:
caminho_arquivo_excel = df_filtered_global_oem
caminho_arquivo_excel['NUMOCORRENCIA'].count()
df_excel = caminho_arquivo_excel [['NUMOS', 'UC','IDSIGFI','NUMOCORRENCIA','NOMECLIENTE','ROTA','STATUS','EXECUTOR','DTCONCLUSAO']]

In [6]:
df_excel

,NUMOS,UC,IDSIGFI,NUMOCORRENCIA,NOMECLIENTE,ROTA,STATUS,EXECUTOR,DTCONCLUSAO
0,202400030344,656957.0,14298,66867,MARIA FRANCISCA CORREIA DA SILVA,8.0,VALIDADO,ONEOM008,2024-05-01 10:18:00
4,202400030302,657946.0,13770,67470,ELISSON PINHEIRO DE ARAUJO,2.0,VALIDADO,ONEOM014,2024-05-01 13:39:00
5,202400030294,660279.0,13790,67471,JESSICA DE LIMA COSTA,2.0,VALIDADO,ONEOM014,2024-05-01 12:40:00
13,202400029171,657909.0,13768,60758,MARIA EDUARDA DE ALMEIDA OLIVEIRA,2.0,VALIDADO,ONEOM009,2024-04-28 11:26:00
14,202400029163,661647.0,15395,59646,MARIA SANDRA OLIVEIRA DOS SANTOS,10.0,VALIDADO,ONEOM005,2024-04-29 06:48:00
...,...,...,...,...,...,...,...,...,...
2371,202300041326,652076.0,14158,169303,ALUIZIO FERREIRA DE SOUZA,3.0,VALIDADO,ONEOM013,2024-01-05 15:48:00
2375,202300041284,652186.0,14000,167025,EZILDO GOMES PINHEIRO,3.0,VALIDADO,ONEOM013,2024-01-13 09:26:00
2376,202300041276,652390.0,14165,166982,ACLINES FERNANDES DA SILVA,3.0,VALIDADO,ONEOM013,2024-01-05 13:38:00
2379,202300041243,656796.0,14007,165610,ANA MARIA XAVIER DE SOUZA,3.0,VALIDADO,ONEOM013,2024-01-07 08:39:00
2420,202300040823,657822.0,14923,166325,NAZIRA FIRMINO DA CUNHA,1.0,VALIDADO,ONEOM002,2024-01-04 16:29:00

## DataFrame a partir do arquivo Excel


#  Passo 3: Comparar os DataFrames para identificar arquivos ausentes no PDF e arquivos não listados no Excel

In [7]:
arquivos_ausentes_no_pdf = df_excel[~df_excel['NUMOCORRENCIA'].isin(df_pdf['NUMOCORRENCIA'])]
arquivos_nao_listados_no_excel = df_pdf[~df_pdf['NUMOCORRENCIA'].isin(df_excel['NUMOCORRENCIA'])]

## Resultados

In [8]:
print(arquivos_ausentes_no_pdf['NUMOCORRENCIA'].count())
display(arquivos_ausentes_no_pdf)

367

,NUMOS,UC,IDSIGFI,NUMOCORRENCIA,NOMECLIENTE,ROTA,STATUS,EXECUTOR,DTCONCLUSAO
0,202400030344,656957.0,14298,66867,MARIA FRANCISCA CORREIA DA SILVA,8.0,VALIDADO,ONEOM008,2024-05-01 10:18:00
4,202400030302,657946.0,13770,67470,ELISSON PINHEIRO DE ARAUJO,2.0,VALIDADO,ONEOM014,2024-05-01 13:39:00
5,202400030294,660279.0,13790,67471,JESSICA DE LIMA COSTA,2.0,VALIDADO,ONEOM014,2024-05-01 12:40:00
13,202400029171,657909.0,13768,60758,MARIA EDUARDA DE ALMEIDA OLIVEIRA,2.0,VALIDADO,ONEOM009,2024-04-28 11:26:00
14,202400029163,661647.0,15395,59646,MARIA SANDRA OLIVEIRA DOS SANTOS,10.0,VALIDADO,ONEOM005,2024-04-29 06:48:00
...,...,...,...,...,...,...,...,...,...
2371,202300041326,652076.0,14158,169303,ALUIZIO FERREIRA DE SOUZA,3.0,VALIDADO,ONEOM013,2024-01-05 15:48:00
2375,202300041284,652186.0,14000,167025,EZILDO GOMES PINHEIRO,3.0,VALIDADO,ONEOM013,2024-01-13 09:26:00
2376,202300041276,652390.0,14165,166982,ACLINES FERNANDES DA SILVA,3.0,VALIDADO,ONEOM013,2024-01-05 13:38:00
2379,202300041243,656796.0,14007,165610,ANA MARIA XAVIER DE SOUZA,3.0,VALIDADO,ONEOM013,2024-01-07 08:39:00
2420,202300040823,657822.0,14923,166325,NAZIRA FIRMINO DA CUNHA,1.0,VALIDADO,ONEOM002,2024-01-04 16:29:00

In [9]:
arquivos_nao_listados_no_excel['NUMOCORRENCIA'].count()
nao_listado_excel = arquivos_nao_listados_no_excel.merge(df_filtered_global_oem, left_on='NUMOCORRENCIA', right_on='NUMOCORRENCIA', how='left' )
nao_listado_excel

Empty DataFrame
Columns: [NUMOS_x, UC_x, IDSIGFI_x, NUMOCORRENCIA, NOMECLIENTE_x, ROTA_x, STATUS_x, EXECUTOR_x, DTCONCLUSAO_x, Unnamed: 0, ORIGEM, TIPO, NUMOS_y, ROTA_y, NOMECLIENTE_y, CPF, CODIGOENERGISA, UC_y, IDSIGFI_y, QDCACCNS, OBRA, TIPODESIGFI, DTCONCLUSAO_y, DTAINC, DTAALT, USUARIOINC, USUARIOALT, STATUS_y, LATLON, LATLONCON, NOMEDAMAE, RECLAMANTE, MUNICIPIO, ENDERECO, COMPETENCIA, CAUSA, TIPOCAUSA, DTAHORARECLAMACAO, EXECUTOR_y, TELEFONES, CONCLUSAO, DIAGNOSTICO, DESCADICIONALPROG, DESCADICIONALEXEC, IDTIPOMANUTENCAO, IDORIGEM, IDTIPOSOLICITACAO, IDCAUSA, IDCONCLUSAO, IDEXECUTOR, IDDIAGNOSTICO, DTINIDESLOCAMENTO, DTCHEGADA, DTAHORAFATO, STATUSSRV, DATACONCLUSAO, IDMOBILE, MANUTENCAO, WHMAX, DATALOG]
Index: []

[0 rows x 60 columns]

In [10]:
recorrence= df_filtered_global_oem.merge(date_duplicated, left_on='NUMOCORRENCIA', right_on='NUMOCORRENCIA', how='left')
recorrence['IDSIGFI'] = recorrence['IDSIGFI'].astype('int')

In [11]:
duplicated_numocorrencia = date_duplicated.merge(df_filtered_global_oem, left_on='NUMOCORRENCIA', right_on='NUMOCORRENCIA', how='left')

In [12]:
print("listar arquivo duplicados:")
print(recorrence.shape)
display(recorrence)

print("listar nº ocorrencia que esta duplicada")
display(sorted(duplicated_numocorrencia['NUMOCORRENCIA']))  

print("Arquivos ausentes na lista de PDF:")
print(arquivos_ausentes_no_pdf.shape)
display(arquivos_ausentes_no_pdf)

print("\nArquivos não listados no Excel:")
print(arquivos_nao_listados_no_excel.shape)
display(arquivos_nao_listados_no_excel)

listar arquivo duplicados:
(380, 52)

,Unnamed: 0,ORIGEM,TIPO,NUMOS,NUMOCORRENCIA,ROTA,NOMECLIENTE,CPF,CODIGOENERGISA,UC,...,IDDIAGNOSTICO,DTINIDESLOCAMENTO,DTCHEGADA,DTAHORAFATO,STATUSSRV,DATACONCLUSAO,IDMOBILE,MANUTENCAO,WHMAX,DATALOG
0,False,ENERGISA,CORRETIVA,202400030344,66867,8.0,MARIA FRANCISCA CORREIA DA SILVA,709.988.842-00,MLPA7722189-22,656957.0,...,34,2024-05-01 10:02:00,2024-05-01 10:02:00,2024-05-01 00:29:00,3,2024-05-01,202400030344,Report2,2666,NaN
1,False,ENERGISA,CORRETIVA,202400030302,67470,2.0,ELISSON PINHEIRO DE ARAUJO,013.507.402-92,MLPA7252641-22,657946.0,...,34,2024-05-01 12:59:00,2024-05-01 12:59:00,2024-04-30 21:08:00,3,2024-05-01,202400030302,Report2,1500,NaN
2,False,ENERGISA,CORRETIVA,202400030294,67471,2.0,JESSICA DE LIMA COSTA,027.755.892-19,MLPA7259299-22,660279.0,...,34,2024-05-01 11:55:00,2024-05-01 11:55:00,2024-04-30 21:04:00,3,2024-05-01,202400030294,Report2,1500,NaN
3,False,ENERGISA,CORRETIVA,202400029171,60758,2.0,MARIA EDUARDA DE ALMEIDA OLIVEIRA,080.968.572-82,MLPA7252639-22,657909.0,...,24,2024-04-28 10:30:00,2024-04-28 10:30:00,2024-04-25 15:19:00,3,2024-04-28,202400029171,Report2,2666,NaN
4,False,ENERGISA,CORRETIVA,202400029163,59646,10.0,MARIA SANDRA OLIVEIRA DOS SANTOS,905.950.252-34,90595025234,661647.0,...,24,2024-04-28 17:02:00,2024-04-28 17:02:00,2024-04-25 15:16:00,3,2024-04-29,202400029163,Report2,2666,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
375,False,ENERGISA,CORRETIVA,202300041326,169303,3.0,ALUIZIO FERREIRA DE SOUZA,021.890.632-30,MLPA7582416-22,652076.0,...,24,2024-01-05 15:39:00,2024-01-05 15:39:00,2023-12-28 18:27:00,3,2024-01-05,202300041326,Report2,2666,NaN
376,False,ENERGISA,CORRETIVA,202300041284,167025,3.0,EZILDO GOMES PINHEIRO,666.463.402-34,MLPA7514808-22,652186.0,...,24,2024-01-13 08:16:00,2024-01-13 08:16:00,2023-12-28 18:20:00,3,2024-01-13,202300041284,Report2,2666,NaN
377,False,ENERGISA,CORRETIVA,202300041276,166982,3.0,ACLINES FERNANDES DA SILVA,70179726277,MLPA7582423-22,652390.0,...,24,2024-01-05 13:11:00,2024-01-05 13:11:00,2023-12-28 18:17:00,3,2024-01-05,202300041276,Report2,2666,NaN
378,False,ENERGISA,CORRETIVA,202300041243,165610,3.0,ANA MARIA XAVIER DE SOUZA,648.877.152-34,MLPA7514816-22,656796.0,...,24,2024-01-07 07:48:00,2024-01-07 07:48:00,2023-12-28 18:13:00,3,2024-01-07,202300041243,Report2,2666,NaN
379,False,ENERGISA,CORRETIVA,202300040823,166325,1.0,NAZIRA FIRMINO DA CUNHA,682.558.532-00,68255853200,657822.0,...,34,2024-01-04 10:09:00,2024-01-04 10:30:00,2023-12-26 10:22:00,3,2024-01-04,202300040823,Report2,2666,NaN

listar nº ocorrencia que esta duplicada

[]

Arquivos ausentes na lista de PDF:
(380, 9)

,NUMOS,UC,IDSIGFI,NUMOCORRENCIA,NOMECLIENTE,ROTA,STATUS,EXECUTOR,DTCONCLUSAO
0,202400030344,656957.0,14298,66867,MARIA FRANCISCA CORREIA DA SILVA,8.0,VALIDADO,ONEOM008,2024-05-01 10:18:00
4,202400030302,657946.0,13770,67470,ELISSON PINHEIRO DE ARAUJO,2.0,VALIDADO,ONEOM014,2024-05-01 13:39:00
5,202400030294,660279.0,13790,67471,JESSICA DE LIMA COSTA,2.0,VALIDADO,ONEOM014,2024-05-01 12:40:00
13,202400029171,657909.0,13768,60758,MARIA EDUARDA DE ALMEIDA OLIVEIRA,2.0,VALIDADO,ONEOM009,2024-04-28 11:26:00
14,202400029163,661647.0,15395,59646,MARIA SANDRA OLIVEIRA DOS SANTOS,10.0,VALIDADO,ONEOM005,2024-04-29 06:48:00
...,...,...,...,...,...,...,...,...,...
2371,202300041326,652076.0,14158,169303,ALUIZIO FERREIRA DE SOUZA,3.0,VALIDADO,ONEOM013,2024-01-05 15:48:00
2375,202300041284,652186.0,14000,167025,EZILDO GOMES PINHEIRO,3.0,VALIDADO,ONEOM013,2024-01-13 09:26:00
2376,202300041276,652390.0,14165,166982,ACLINES FERNANDES DA SILVA,3.0,VALIDADO,ONEOM013,2024-01-05 13:38:00
2379,202300041243,656796.0,14007,165610,ANA MARIA XAVIER DE SOUZA,3.0,VALIDADO,ONEOM013,2024-01-07 08:39:00
2420,202300040823,657822.0,14923,166325,NAZIRA FIRMINO DA CUNHA,1.0,VALIDADO,ONEOM002,2024-01-04 16:29:00

Arquivos não listados no Excel:
(0, 9)

Empty DataFrame
Columns: [NUMOS, UC, IDSIGFI, NUMOCORRENCIA, NOMECLIENTE, ROTA, STATUS, EXECUTOR, DTCONCLUSAO]
Index: []

In [ ]:
#Salvando a planilha Manutenções Energisa_preventiva para ser enviadas em Excell( .xlsx)
dataframe_excel = pd.ExcelWriter(r"D:\OEM\output\csv_ausentes_corretivas_1_TRANCHE-geral.xlsx")
arquivos_ausentes_no_pdf.to_excel(dataframe_excel)
dataframe_excel.close()